### ISSUE TITLE
Audio playback with hiccups

### ISSUE THREAD

**Issue by oCanna** [MusicGenerator/mumble-ruby-pluginbot#237]
Hello,

I have a problem with my music bot which I don't know how to solve.
I attached a short video which demonstrates the problem. It isn't neither the murmurd nor the mumble-client which causes this. I've tested it with vlc + virtual audio cable and it plays fine without any hiccups.

Any idea what could cause this problem?

Tested on ubuntu 14.04
with mpd 0.18.7 and 0.20.11
and murmurd 1.2.19 and master-fba1d65
and mumble 1.2.19 (x86) and 1.3.0~2586~g894ade2 (x86_64)

Everything runs in my local network.

[2017-11-21 17-24-31.zip](https://github.com/MusicGenerator/mumble-ruby-pluginbot/files/1492347/2017-11-21.17-24-31.zip)

**Comment by dafoxia** [comment]
I saw you use it on a vdr :D which distribution? Or is the vdr self buildt?
Btw. I've also seen it's run on a xen hypervisor. This is'nt tested yet by us, but should run, since it runs on a virtualbox also fine.
I'm not familar with Xen, is there an easy way to set up a system booting on a usb drive (stick, or hdd)? I will test this scenario, but I need a link for an howto. ;)

**Comment by oCanna** [comment]
I can test it on bare metal tomorrow, both the murmurd and the pluginbot.
I have a vdr client (ubuntu 16.04.3 core i3) where I could run it.

My vdr packages are borrowed from the yavdr distribution :)

**Comment by oCanna** [comment]
So i've tested the pluginbot on my ubuntu 16.04.3 machine and it runs flawless when connected to murmurd running on the xen vm. It has to be some kind of performence issue related to my xen setup either cause by the ruby pluginbot or mpd. Rising the priority levels (nice, ionice) on both mpd and ruby doesn't help either.

I think this issue can be closed and I will look into updating my xen machine in the near future hoping that this issue will be solved.

**Comment by dafoxia** [comment]
Maybe the hiccup caused by the pluginbot / murmur connection. Audio packets sends during TCP instead of UDP since I've not the skill for updating mumble-ruby to send in UDP. I don't know if TCP packets are bufferd by the client's as done with UDP. If no buffer is in the client late packets will dropped. UDP transfer is bufferd since they must been orderd before they played by the client.

Reopen this if issue not solved by updated xen machine. :)
